name: Node
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.16.0, 17.x, 18.x, latest]
        include:
        - node-version: 12.21.0
          experimental: true
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm test
